apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-root-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kamolhasan/introduction-to-argocd.git'
    targetRevision: HEAD
    path: applications
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
