apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kamolhasan/introduction-to-argocd.git
    targetRevision: HEAD
    path: yamls/applications
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true # Automatically delete resources that are no longer in Git
      selfHeal: true # Automatically update resources that have drifted from Git
      allowEmpty: false # Do not allow an empty spec
    syncOptions:
      - Validate=false
      - Prune=true
      - SyncInterval=10s
