apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.10
          ports:
            - containerPort: 80
  strategy:
    canary:
      steps:
        - setWeight: 30
        - pause: { duration: 15s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
